services:
  db:
    image: postgres:15
    container_name: osintmap_db
    environment:
      POSTGRES_DB: osintmap
      POSTGRES_USER: osint
      POSTGRES_PASSWORD: osintpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    container_name: osintmap_backend
    working_dir: /app/backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://osint:osintpassword@db:5432/osintmap
      PORT: 4000
    depends_on:
      - db
    ports:
      - "4000:4000"
    command: sh -c "until npm run prisma:migrate; do echo 'DB not ready, retry in 3s'; sleep 3; done; npm run dev"
    restart: always
  frontend:
    build:
      context: ./frontend
    container_name: osintmap_frontend
    working_dir: /app/frontend
    environment:
      VITE_API_BASE_URL: http://backend:4000/api
    depends_on:
      - backend
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0


volumes:
  pgdata: